import sys
import os
import math
from PyQt5.QtCore import pyqtSignal
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *

class ClickableLineEdit(QLineEdit):
    clicked = pyqtSignal()
    def mousePressEvent(self, event):
        self.clicked.emit()
        QLineEdit.mousePressEvent(self, event)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1421, 930)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
# -------------------pict------------------------------------------------------
        self.Y_W = QtWidgets.QLabel(self.centralwidget)
        self.Y_W.setGeometry(QtCore.QRect(390, 20, 1000, 405))
        self.Y_W.setText("")
        self.Y_W.setPixmap(QtGui.QPixmap("img/Y_W.png"))
        self.Y_W.setScaledContents(True)
        self.Y_W.setObjectName("Y_W")

        self.Y_L = QtWidgets.QLabel(self.centralwidget)
        self.Y_L.setGeometry(QtCore.QRect(390, 500, 1000, 405))
        self.Y_L.setText("")
        self.Y_L.setPixmap(QtGui.QPixmap("img/Y_L.png"))
        self.Y_L.setScaledContents(True)
        self.Y_L.setObjectName("Y_L")

        rx = QtCore.QRegExp("[0-9]{4}")
        val = QtGui.QRegExpValidator(rx)
# -------------------------input--------------------------------------
        self.length_txt = QtWidgets.QLabel(self.centralwidget)
        self.length_txt.setGeometry(QtCore.QRect(30, 60, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.length_txt.setFont(font)
        self.length_txt.setObjectName("length_txt")

        self.width_txt = QtWidgets.QLabel(self.centralwidget)
        self.width_txt.setGeometry(QtCore.QRect(30, 120, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.width_txt.setFont(font)
        self.width_txt.setObjectName("width_txt")

        self.height_txt = QtWidgets.QLabel(self.centralwidget)
        self.height_txt.setGeometry(QtCore.QRect(30, 180, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.height_txt.setFont(font)
        self.height_txt.setObjectName("height_txt")

        self.length_inp = ClickableLineEdit(self.centralwidget)
        self.length_inp.setGeometry(QtCore.QRect(240, 60, 104, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.length_inp.setFont(font)
        self.length_inp.setObjectName("length_inp")
        self.length_inp.setValidator(val)
        self.length_inp.clicked.connect(self.length_inp.clear)

        self.width_inp = ClickableLineEdit(self.centralwidget)
        self.width_inp.setGeometry(QtCore.QRect(240, 120, 104, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.width_inp.setFont(font)
        self.width_inp.setObjectName("width_inp")
        self.width_inp.setValidator(val)
        self.width_inp.clicked.connect(self.width_inp.clear)

        self.height_inp = ClickableLineEdit(self.centralwidget)
        self.height_inp.setGeometry(QtCore.QRect(240, 180, 104, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.height_inp.setFont(font)
        self.height_inp.setObjectName("height_inp")
        self.height_inp.setValidator(val)
        self.height_inp.clicked.connect(self.height_inp.clear)
# -------------------------------radio-------------------------------------------------------
        self.radio_B = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_B.setGeometry(QtCore.QRect(30, 290, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_B.sizePolicy().hasHeightForWidth())
        self.radio_B.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.radio_B.setFont(font)
        self.radio_B.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.radio_B.setTabletTracking(True)
        self.radio_B.setAutoFillBackground(False)
        self.radio_B.setIconSize(QtCore.QSize(20, 20))
        self.radio_B.setChecked(False)
        self.radio_B.setObjectName("radio_B")

        self.radio_E = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_E.setGeometry(QtCore.QRect(30, 360, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_E.sizePolicy().hasHeightForWidth())
        self.radio_E.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.radio_E.setFont(font)
        self.radio_E.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.radio_E.setTabletTracking(True)
        self.radio_E.setAutoFillBackground(False)
        self.radio_E.setIconSize(QtCore.QSize(20, 20))
        self.radio_E.setChecked(False)
        self.radio_E.setObjectName("radio_E")

        self.radio_BC = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_BC.setGeometry(QtCore.QRect(200, 360, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_BC.sizePolicy().hasHeightForWidth())
        self.radio_BC.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.radio_BC.setFont(font)
        self.radio_BC.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.radio_BC.setTabletTracking(True)
        self.radio_BC.setAutoFillBackground(False)
        self.radio_BC.setIconSize(QtCore.QSize(20, 20))
        self.radio_BC.setChecked(False)
        self.radio_BC.setObjectName("radio_BC")

        self.radio_EB = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_EB.setGeometry(QtCore.QRect(200, 290, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_EB.sizePolicy().hasHeightForWidth())
        self.radio_EB.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.radio_EB.setFont(font)
        self.radio_EB.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.radio_EB.setTabletTracking(True)
        self.radio_EB.setAutoFillBackground(False)
        self.radio_EB.setIconSize(QtCore.QSize(20, 20))
        self.radio_EB.setChecked(False)
        self.radio_EB.setObjectName("radio_EB")
# ---------------------------------info_line-----------------------------------------------
        self.info_line_txt = QtWidgets.QLabel(self.centralwidget)
        self.info_line_txt.setGeometry(QtCore.QRect(20, 500, 361, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.info_line_txt.setFont(font)
        self.info_line_txt.setScaledContents(True)
        self.info_line_txt.setObjectName("info_line_txt")

        self.line_EVOL = QtWidgets.QLabel(self.centralwidget)
        self.line_EVOL.setGeometry(QtCore.QRect(720, 240, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.line_EVOL.setFont(font)
        self.line_EVOL.setObjectName("line_EVOL")

        self.line_EVOL_2 = QtWidgets.QLabel(self.centralwidget)
        self.line_EVOL_2.setGeometry(QtCore.QRect(1010, 720, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.line_EVOL_2.setFont(font)
        self.line_EVOL_2.setObjectName("line_EVOL_2")

        self.line_618 = QtWidgets.QLabel(self.centralwidget)
        self.line_618.setGeometry(QtCore.QRect(20, 550, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.line_618.setFont(font)
        self.line_618.setObjectName("line_618")

        self.line_924 = QtWidgets.QLabel(self.centralwidget)
        self.line_924.setGeometry(QtCore.QRect(20, 600, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.line_924.setFont(font)
        self.line_924.setObjectName("line_924")

        self.line_1228 = QtWidgets.QLabel(self.centralwidget)
        self.line_1228.setGeometry(QtCore.QRect(20, 650, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.line_1228.setFont(font)
        self.line_1228.setObjectName("line_1228")

        self.line_bobst = QtWidgets.QLabel(self.centralwidget)
        self.line_bobst.setGeometry(QtCore.QRect(20, 720, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.line_bobst.setFont(font)
        self.line_bobst.setObjectName("line_bobst")

        self.square_m2 = QtWidgets.QLabel(self.centralwidget)
        self.square_m2.setGeometry(QtCore.QRect(20, 430, 361, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.square_m2.setFont(font)
        self.square_m2.setScaledContents(True)
        self.square_m2.setObjectName("square_m2")
# ---------------------------output Y_W-------------------------------------------------------
        self.YW_w1 = QtWidgets.QLabel(self.centralwidget)
        self.YW_w1.setGeometry(QtCore.QRect(540, 70, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.YW_w1.setFont(font)
        self.YW_w1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.YW_w1.setAutoFillBackground(False)
        self.YW_w1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.YW_w1.setScaledContents(True)
        self.YW_w1.setAlignment(QtCore.Qt.AlignCenter)
        self.YW_w1.setObjectName("YW_w1")

        self.YW_l1 = QtWidgets.QLabel(self.centralwidget)
        self.YW_l1.setGeometry(QtCore.QRect(760, 70, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.YW_l1.setFont(font)
        self.YW_l1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.YW_l1.setAutoFillBackground(False)
        self.YW_l1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.YW_l1.setScaledContents(True)
        self.YW_l1.setAlignment(QtCore.Qt.AlignCenter)
        self.YW_l1.setObjectName("YW_l1")

        self.YW_w2 = QtWidgets.QLabel(self.centralwidget)
        self.YW_w2.setGeometry(QtCore.QRect(980, 70, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.YW_w2.setFont(font)
        self.YW_w2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.YW_w2.setAutoFillBackground(False)
        self.YW_w2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.YW_w2.setScaledContents(True)
        self.YW_w2.setAlignment(QtCore.Qt.AlignCenter)
        self.YW_w2.setObjectName("YW_w2")

        self.YW_l2 = QtWidgets.QLabel(self.centralwidget)
        self.YW_l2.setGeometry(QtCore.QRect(1210, 70, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.YW_l2.setFont(font)
        self.YW_l2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.YW_l2.setAutoFillBackground(False)
        self.YW_l2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.YW_l2.setScaledContents(True)
        self.YW_l2.setAlignment(QtCore.Qt.AlignCenter)
        self.YW_l2.setObjectName("YW_l2")

        self.YW_work_H = QtWidgets.QLabel(self.centralwidget)
        self.YW_work_H.setGeometry(QtCore.QRect(370, 180, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.YW_work_H.setFont(font)
        self.YW_work_H.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.YW_work_H.setAutoFillBackground(False)
        self.YW_work_H.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.YW_work_H.setScaledContents(True)
        self.YW_work_H.setAlignment(QtCore.Qt.AlignCenter)
        self.YW_work_H.setObjectName("YW_work_H")

        self.YW_k = QtWidgets.QLabel(self.centralwidget)
        self.YW_k.setGeometry(QtCore.QRect(430, 360, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.YW_k.setFont(font)
        self.YW_k.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.YW_k.setAutoFillBackground(False)
        self.YW_k.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.YW_k.setScaledContents(True)
        self.YW_k.setAlignment(QtCore.Qt.AlignCenter)
        self.YW_k.setObjectName("YW_k")

        self.YW_h = QtWidgets.QLabel(self.centralwidget)
        self.YW_h.setGeometry(QtCore.QRect(430, 250, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.YW_h.setFont(font)
        self.YW_h.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.YW_h.setAutoFillBackground(False)
        self.YW_h.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.YW_h.setScaledContents(True)
        self.YW_h.setAlignment(QtCore.Qt.AlignCenter)
        self.YW_h.setObjectName("YW_h")

        self.YW_work_l = QtWidgets.QLabel(self.centralwidget)
        self.YW_work_l.setGeometry(QtCore.QRect(880, 30, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.YW_work_l.setFont(font)
        self.YW_work_l.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.YW_work_l.setAutoFillBackground(False)
        self.YW_work_l.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.YW_work_l.setScaledContents(True)
        self.YW_work_l.setAlignment(QtCore.Qt.AlignCenter)
        self.YW_work_l.setObjectName("YW_work_l")
# _____________________________output Y_L___________________________________________________________
        self.YL_l2 = QtWidgets.QLabel(self.centralwidget)
        self.YL_l2.setGeometry(QtCore.QRect(600, 550, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.YL_l2.setFont(font)
        self.YL_l2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.YL_l2.setAutoFillBackground(False)
        self.YL_l2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.YL_l2.setScaledContents(True)
        self.YL_l2.setAlignment(QtCore.Qt.AlignCenter)
        self.YL_l2.setObjectName("YL_l2")

        self.YL_work_H = QtWidgets.QLabel(self.centralwidget)
        self.YL_work_H.setGeometry(QtCore.QRect(370, 660, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.YL_work_H.setFont(font)
        self.YL_work_H.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.YL_work_H.setAutoFillBackground(False)
        self.YL_work_H.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.YL_work_H.setScaledContents(True)
        self.YL_work_H.setAlignment(QtCore.Qt.AlignCenter)
        self.YL_work_H.setObjectName("YL_work_H")

        self.YL_h = QtWidgets.QLabel(self.centralwidget)
        self.YL_h.setGeometry(QtCore.QRect(430, 720, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.YL_h.setFont(font)
        self.YL_h.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.YL_h.setAutoFillBackground(False)
        self.YL_h.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.YL_h.setScaledContents(True)
        self.YL_h.setAlignment(QtCore.Qt.AlignCenter)
        self.YL_h.setObjectName("YL_h")

        self.YL_work_L = QtWidgets.QLabel(self.centralwidget)
        self.YL_work_L.setGeometry(QtCore.QRect(900, 510, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.YL_work_L.setFont(font)
        self.YL_work_L.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.YL_work_L.setAutoFillBackground(False)
        self.YL_work_L.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.YL_work_L.setScaledContents(True)
        self.YL_work_L.setAlignment(QtCore.Qt.AlignCenter)
        self.YL_work_L.setObjectName("YL_work_L")

        self.YL_w2 = QtWidgets.QLabel(self.centralwidget)
        self.YL_w2.setGeometry(QtCore.QRect(830, 550, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.YL_w2.setFont(font)
        self.YL_w2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.YL_w2.setAutoFillBackground(False)
        self.YL_w2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.YL_w2.setScaledContents(True)
        self.YL_w2.setAlignment(QtCore.Qt.AlignCenter)
        self.YL_w2.setObjectName("YL_w2")

        self.YL_k = QtWidgets.QLabel(self.centralwidget)
        self.YL_k.setGeometry(QtCore.QRect(430, 840, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.YL_k.setFont(font)
        self.YL_k.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.YL_k.setAutoFillBackground(False)
        self.YL_k.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.YL_k.setScaledContents(True)
        self.YL_k.setAlignment(QtCore.Qt.AlignCenter)
        self.YL_k.setObjectName("YL_k")

        self.YL_l1 = QtWidgets.QLabel(self.centralwidget)
        self.YL_l1.setGeometry(QtCore.QRect(1050, 550, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.YL_l1.setFont(font)
        self.YL_l1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.YL_l1.setAutoFillBackground(False)
        self.YL_l1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.YL_l1.setScaledContents(True)
        self.YL_l1.setAlignment(QtCore.Qt.AlignCenter)
        self.YL_l1.setObjectName("YL_l1")

        self.YL_w1 = QtWidgets.QLabel(self.centralwidget)
        self.YL_w1.setGeometry(QtCore.QRect(1270, 550, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.YL_w1.setFont(font)
        self.YL_w1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.YL_w1.setAutoFillBackground(False)
        self.YL_w1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.YL_w1.setScaledContents(True)
        self.YL_w1.setAlignment(QtCore.Qt.AlignCenter)
        self.YL_w1.setObjectName("YL_w1")
# ----------------------output koef-------------------------------------------
        self.L_div_W = QtWidgets.QLabel(self.centralwidget)
        self.L_div_W.setGeometry(QtCore.QRect(670, 450, 220, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.L_div_W.setFont(font)
        self.L_div_W.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.L_div_W.setAutoFillBackground(False)
        self.L_div_W.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.L_div_W.setScaledContents(True)
        self.L_div_W.setAlignment(QtCore.Qt.AlignCenter)
        self.L_div_W.setObjectName("L_div_W")

        self.H_div_L = QtWidgets.QLabel(self.centralwidget)
        self.H_div_L.setGeometry(QtCore.QRect(900, 450, 220, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.H_div_L.setFont(font)
        self.H_div_L.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.H_div_L.setAutoFillBackground(False)
        self.H_div_L.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.H_div_L.setScaledContents(True)
        self.H_div_L.setAlignment(QtCore.Qt.AlignCenter)
        self.H_div_L.setObjectName("H_div_L")

        self.H_div_W = QtWidgets.QLabel(self.centralwidget)
        self.H_div_W.setGeometry(QtCore.QRect(1130, 450, 220, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.H_div_W.setFont(font)
        self.H_div_W.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.H_div_W.setAutoFillBackground(False)
        self.H_div_W.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.H_div_W.setScaledContents(True)
        self.H_div_W.setAlignment(QtCore.Qt.AlignCenter)
        self.H_div_W.setObjectName("H_div_W")

        self.L_plus_W = QtWidgets.QLabel(self.centralwidget)
        self.L_plus_W.setGeometry(QtCore.QRect(440, 450, 220, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.L_plus_W.setFont(font)
        self.L_plus_W.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.L_plus_W.setAutoFillBackground(False)
        self.L_plus_W.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.L_plus_W.setScaledContents(True)
        self.L_plus_W.setAlignment(QtCore.Qt.AlignCenter)
        self.L_plus_W.setObjectName("L_plus_W")

# ------------------------------button------------------------------
        self.Button = QtWidgets.QPushButton(self.centralwidget)
        self.Button.setGeometry(QtCore.QRect(40, 810, 251, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        self.Button.setFont(font)
        self.Button.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.Button.setObjectName("Button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.length_txt.setText(_translate("MainWindow", "Длина (L)"))
        self.width_txt.setText(_translate("MainWindow", "Ширина (W)"))
        self.height_txt.setText(_translate("MainWindow", "Высота (H)"))
        self.radio_B.setText(_translate("MainWindow", "B(C)"))
        self.radio_E.setText(_translate("MainWindow", "E"))
        self.radio_BC.setText(_translate("MainWindow", "BC"))
        self.radio_EB.setText(_translate("MainWindow", "EB"))
        self.info_line_txt.setText(_translate("MainWindow", "Возможные линии изготовления"))
        self.line_EVOL.setText(_translate("MainWindow", "EVOL-100"))
        self.line_618.setText(_translate("MainWindow", "FFG-618"))
        self.line_924.setText(_translate("MainWindow", "FFG-924"))
        self.line_1228.setText(_translate("MainWindow", "FFG-1228"))
        self.line_bobst.setText(_translate("MainWindow", "только штампом"))
        self.square_m2.setText(_translate("MainWindow", "Площадь "))
        self.YW_w1.setText(_translate("MainWindow", "W1"))
        self.YW_l1.setText(_translate("MainWindow", "L1"))
        self.YW_w2.setText(_translate("MainWindow", "W2"))
        self.YW_l2.setText(_translate("MainWindow", "L2"))
        self.YW_work_H.setText(_translate("MainWindow", "work_H"))
        self.YW_k.setText(_translate("MainWindow", "K"))
        self.YW_h.setText(_translate("MainWindow", "H"))
        self.L_plus_W.setText(_translate("MainWindow", "L + W"))
        self.YL_l2.setText(_translate("MainWindow", "L2"))
        self.YL_work_H.setText(_translate("MainWindow", "work_H"))
        self.YL_h.setText(_translate("MainWindow", "H"))
        self.YL_work_L.setText(_translate("MainWindow", "work_L"))
        self.YL_w2.setText(_translate("MainWindow", "W2"))
        self.YL_k.setText(_translate("MainWindow", "K"))
        self.YL_l1.setText(_translate("MainWindow", "L1"))
        self.YL_w1.setText(_translate("MainWindow", "W1"))
        self.L_div_W.setText(_translate("MainWindow", "L / W"))
        self.H_div_L.setText(_translate("MainWindow", "H / L"))
        self.H_div_W.setText(_translate("MainWindow", "H / W"))
        self.YW_work_l.setText(_translate("MainWindow", "work_L"))
        self.line_EVOL_2.setText(_translate("MainWindow", "EVOL-100"))
        self.Button.setText(_translate("MainWindow", "Расчет"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
